<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DueGooder.Connectors\DueGooder.Connectors.csproj" />
    <ProjectReference Include="..\..\src\DueGooder.Infrastructure\DueGooder.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\DueGooder.Application\DueGooder.Application.csproj" />
    <ProjectReference Include="..\..\src\DueGooder.Domain\DueGooder.Domain.csproj" />
  </ItemGroup>

</Project>